### ISSUE TITLE
Grooming sprint 20

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#402]
- Continue improving IMAP performance
- Tmail setting
  - automatic MDN option request for each mail sent
  - mail forwarding
  - User profiles (well we have identities in jmap though)... we drop the avatars right?
  - Roles..?
  - On an other note, not related to esn, will still need to deal with delegation some day as well :)m

**Comment by chibenwa** [comment]
My takes on the topic https://github.com/linagora/james-project-private/issues/87

**Comment by chibenwa** [comment]
## TODO

 - [ ] ADR forward ? (something tiny...)
 - [ ] JMAP spec for forward
 - [ ] JMAP spec for "always request MDNs"
 - [ ] Ticket: Implement JMAP forward extension
 - [ ] Ticket: Implement always request MDNs
 - [ ] Ticket: Document new JMAP extensions
 - [ ] Ticket: Fasten ES indexation
 - IMAP Search tickets...
 - Other stuff related to IMAP performance if relevant.

**Comment by chibenwa** [comment]
Drop "always request MDNs" -> likely a useless feature.

 - [ ] Create "MDN" story for TMAIL frontend (check)

**Comment by chibenwa** [comment]
- [ ] ES indexing perf: flattened mapping?
