### ISSUE TITLE
[EPIC] Labels

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#632]
## Feature

We need to be able to : 

 - List specific keywords used by a user (so that UI can list it in the left panel)
 - Manage color (default color is managed in the frontend)
 - Interop with Thunderbird tags?
 - Avoid (filter out) common userFlags ($Forwarded, $Junk, TB fishing, etc...). Does TB uses a prefix?

## Technical details

Write an extension for managing labels.

Used to get the list of `label` by the clients.

Label structure:

```
PK username
CK id (hash of the name of the label)
C name
C color
```

API:

```
record Label(Keyword keyword, Optional<Color> color);

interface LabelRepository {
    Mono<Void> addLabels(User user, Collection<Label> label); // with the color
    Mono<Void> updateLabel(User user, Keyword userFlag, Color color);
    Flux<Label>  listLabels(User user)
}
```

Populate via mailbox listener.

Method:
 - `Label/get` 
 - `Label/set`: create, update (color only)
 - `Label/changes` -> Design it in order to estimate its cost...
 
 ## TODO

 - [ ] Write an formal extension for it.
 - [ ] Investigate TB label stucture
 - [ ] Outlook label ? -> See with QUANG
 - [ ] Careful about delegation, shared mailboxes. => BTE to write user stories.

**Comment by quantranhong1999** [comment]
- [ ] ADR for label feature
- [ ] JMAP extension specification
- [ ] LabelRepository interface + memory implementation
- [ ] Cassandra implementation of LabelRepository
- [ ] Label/get
- [ ] Label/set create
- [ ] Label/set update
- [ ] Label/changes
- [ ] Mailbox listener to populate labels (when creating keywords)
- [ ] Handle delegation/shared mailboxes: 
   - shared mailboxes: everyone should have the same label while one creates a label
   - delegation case: delegatees should be able to create/list labels on the delegator account
- [ ] Demo with TB, outlook

**Comment by quantranhong1999** [comment]
I experimented a bit with mapping between Thunderbird IMAP tags and TMail JMAP keywords.

Thunderbirds tags:
![tags](https://github.com/linagora/tmail-backend/assets/55171818/d5683743-28f0-46e0-ae00-9ca2ab9adeda)

JMAP keywords:
```json
"keywords": {
	"nonjunk": true,
        "junk": true,
	"$label3": true,
	"$label4": true,
	"$label5": true,
	"$label1": true,
	"custom_tag_1": true,
	"$label2": true,
	"$seen": true,
	"custom_tag_2": true
}
```

Cases:
- Default tags of Thunderbird (Important, Work, Personal, To Do, Later) <-> `$label1` -> `$label5` on JMAP.
- IMAP tag `Custom Tag 1` <-> JMAP keyword `custom_tag_1`.
- IMAP tag `Custom_Tag_2` <-> JMAP keyword `custom_tag_2`.
- Thunderbird `junk` / `nonjunk` tag seems not to follow [the standard](https://www.iana.org/assignments/imap-jmap-keywords/imap-jmap-keywords.xhtml). Should be `$junk`/`$notjunk`.
- A IMAP tag with non-ASCII chars `Việt Tag` seems somehow still supported by Thunderbird, but not by JMAP (just normally following JMAP standard).
  
Summary:
- It seems Thunderbird stores the mapping between the tags beautiful name e.g. `Important` -> the server tag `$label1` on the client machine.
   => It's tricky for JMAP to get the "beautiful name" of the label (to display them).
- We may need to filter out custom tags of Thunderbird also. E.g `junk`, `nonjunk`.
- We likely would skip non-standard JMAP keywords e.g `Vỉệt Tag`.

**Comment by chibenwa** [comment]
1. What happens if you create a custom keyword without a corresponding label in THunderbird?

**Comment by quantranhong1999** [comment]
> What happens if you create a custom keyword without a corresponding label in THunderbird?

I created a keyword by JMAP.
Thunderbird does not display/ not allow filtering by that keyword.

**Comment by chibenwa** [comment]
Ok so inter-operability with TB => impossible!

**Comment by quantranhong1999** [comment]
`shared mailboxes: everyone should have the same label while one creates a label` Why @vttranlina ?

IMO labels belong to accounts rather than mailboxes. 
If ALICE shared a mailbox with BOB, then BOB creates a Label (may not be related to the shared mailbox usage), so IMO ALICE tags should not be polluted by other users' tags.

We may think about something like a team label? But somehow a label is similar to a mailbox, and given we had team mailboxes, I do not think we really need something like label for team.

**Comment by chibenwa** [comment]
You are right @quantranhong1999 with another indirection level we actually make it impossible to share labels (related to account) in team-mailboxes.

IMAP proposes per user message flags but James have no such capabilities that would anyway be expensive.

So if we go down that way we likely should avoid this edge case altogether and ignore labels in shared mailboxes.

**Comment by vttranlina** [comment]
> I do not think we really need something like label for team.

I agree, 

> IMO labels belong to accounts rather than mailboxes.

yes, Thunderbird lists tags by account, not by mailbox

**Comment by quantranhong1999** [comment]
> ignore labels in shared mailboxes.

Hmm, so do we still support individual labels on shared mailboxes?

E.g: BOB and ALICE have access to the shared mailbox S which has a message M.
BOB set a label `IMPORTANT_BOB` on the message M, and ALICE set a label `IMPORTANT_ALICE` on the message M.
Should BOB still see message M in his label `IMPORTANT_BOB`, and the same for ALICE?

**Comment by chibenwa** [comment]
We `could` add a postfix to the label keyword, eg:

`Important for bob` -> `$label1-[hash(bob)]`
`Important for alice` -> `$label1-[hash(alice)]`

this would allow bob and alice to independantly set labels in a shared mailbox....

> Should BOB still see message M in his label IMPORTANT_BOB, and the same for ALICE?

Both are possible in IMAP. It is down to the server to chose what to do: with **flags** do you want to be shared, to be personnal?

In james all flags are "shared"...
