### ISSUE TITLE
[Postgres] TMail pg-app - TODO remain

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#895]
When doing task https://github.com/linagora/tmail-backend/issues/883, something is not ready. 
We need to TODO it 

- [x] Choose RspamdModule (it depends on MessageIdManager https://github.com/linagora/james-project/issues/5016) & Create a new module `postgres-healthcheck-integration-tests` for test

- [x] Refactor Guice binding for choose User Module (comment https://github.com/linagora/tmail-backend/pull/892#discussion_r1452079962) after pr https://github.com/apache/james-project/pull/1919 

- [x] combined-identity-api for generic code, then a module for cassandra implem, one for postgres

**Comment by vttranlina** [comment]
PR https://github.com/linagora/tmail-backend/pull/899
